In [2]:
#!pip install pandas
#!pip install numpy 

import pandas as pd
import numpy as np

# Array



In [38]:
python_list = [1,2,3,4,5,6]
python_list[::1]

[1, 2, 3, 4, 5, 6]

In [39]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [40]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [20]:
python_list = [[1,1,2]]
print(type(python_list))

<class 'list'>


In [22]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

In [30]:
i = np.array([[1, 2, 3],
              [4, 5, 6]])

print("tipo: ", type(i))
print("shape: ", i.shape)
print("dimensoes: ", i.ndim)
print(i)

tipo:  <class 'numpy.ndarray'>
shape:  (2, 3)
dimensoes:  2
[[1 2 3]
 [4 5 6]]


In [7]:
# Multiplicação de index por index
a * b

array([3, 4, 3])

In [16]:
# Produto vetorial

print(a @ b)
print(a.dot(b))


10
10


# Exercicíos

In [43]:
# 8. Reverse a vector (first element becomes last) (★☆☆)
vector = np.arange(0,10,1)
vector[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [45]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
vector = np.array([[0,1,2],
                  [3,4,5],
                  [6,7,8]])

In [54]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

In [48]:
# 11. Create a 3x3 identity matrix (★☆☆)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [52]:
# 12. Create a 3x3x3 array with random values (★☆☆)
np.random.rand(3,3)

array([[0.16036474, 0.87938108, 0.71682237],
       [0.16031574, 0.08525618, 0.18509208],
       [0.54373169, 0.4897791 , 0.28469638]])

In [63]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
x = np.random.rand(10,10)
print("Max: ", np.amax(x))
print("Min: ", np.amin(x))

Max:  0.9993748377900112
Min:  0.0011790080752412946


In [64]:
# 14 Create a 2d array with 1 on the border and 0 inside (★☆
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [94]:
# 15 How to add a border (filled with 0s) aroud an existing array?
x = np.ones((5,5))
x[0:1,:] = 0
x[:,0:1] = 0
x[:,-1:] = 0
x[-1:,:] = 0
print(x)

# OU

x = np.zeros((5,5))
x[1:-1,1:-1] = 1
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [99]:
# 16 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
